packs:
  packname_example:
    money: 10.0         #Optional
    items:
    - stone_bricks/20   #ItemName/Quantity
    - planks/5/2        #ItemName/Quantity/SubId
    commands:
    - "say Say_Command_Example!"
    tellraws:
      @a: "Tellraw for @a !"
      player: "Tellraw for player who bought the pack!"
    
    
messages:
  reload: "ยง2Configuration reloaded!"
  nopermission: "ยง4You can't do that!"
  noexist: "ยง4This pack doesn't exist!"
  arguments: "ยง4Please provide a minimum of 2 arguments in the command !"